# For hot reloading
version: '3'
services:
    app:
        container_name: dotnet_watch_docker_example
        image: mcr.microsoft.com/dotnet/sdk:6.0
        ports:
            - 5000:5000
        volumes:
            - .:/app
        working_dir: /app
        command: dotnet watch run --no-restore --urls "http://+:5000"