apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer
  namespace: default
spec:
  ports:
  type: NodePort
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer
