apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-app
  labels:
    app: blazor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor-app
  template:
    metadata:
      labels:
        app: blazor-app
    spec:
      containers:
      - name: blazor-app
        image: blazor-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blazor-app
  name: blazor-app
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blazor-app