apiVersion: v1
kind: Service
metadata:
  labels:
    app: blazor-app
  name: blazor-app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blazor-app
  type: ClusterIP
