resources:
- blazor-app.deployment.yaml
- blazor-app.service.yaml
- redis.deployment.yaml
- redis.service.yaml
- redisinsight.deployment.yaml
- redisinsight.service.yaml
- postgres.deployment.yaml
- postgres.service.yaml
- adminer.deployment.yaml
- adminer.service.yaml